const ARCHITECTURE_GRAPH_MAX_BYTES: u64 = 2 * 1024 * 1024;
const ARCHITECTURE_GRAPH_ID_MAX: usize = 96;
const ARCHITECTURE_AGENT_GUIDE_FILENAME: &str = "AGENTS.md";
const ARCHITECTURE_ICON_REFERENCE_FILENAME: &str = "icon-aliases.json";

const ARCHITECTURE_AGENT_GUIDE: &str = r##"# Diff Forge Architectures

Architecture graphs are first-class Diff Forge agent artifacts. They are not generic Markdown docs, Draw.io files, or README sections unless the user explicitly asks for those.

## Where graphs live

- Repo-scoped architecture files live under `.agents/architectures/graphs/*.arch` in the selected repo.
- `.agents/architectures/index.json` is generated by Diff Forge.
- `.agents/architectures/AGENTS.md` and `.agents/architectures/icon-aliases.json` are generated reference files for agents.

When a user asks for an architecture, diagram, system map, deployment view, data flow, auth flow, billing/subscription flow, or subsystem visualization, create or update a `.arch` graph in `.agents/architectures/graphs/`.

## Agent workflow

Call `coordination-kernel.architecture_context` before architecture, diagram, deployment, flow, or subsystem visualization work. Use `coordination-kernel.architecture_list` to discover existing graphs and `coordination-kernel.architecture_icon_reference` when choosing icons. Create or modify `.agents/architectures/graphs/*.arch` with normal file edits so the Architecture tab reloads file changes live.

1. Inspect `.agents/architectures/index.json` and existing `graphs/*.arch` files before creating a new graph.
2. Prefer modifying the most relevant existing graph when the work changes a known subsystem.
3. Create a new graph file only when there is no relevant existing graph.
4. Write nodes and containers first, then edges.
5. Save the `.arch` file incrementally after each valid block. Diff Forge reloads valid graph source live in the Architecture tab.
6. Keep titles human-readable. The title, not a separate type field, should explain the graph's purpose.
7. Do not create `ARCHITECTURE.md`, `docs/architecture.md`, Draw.io, SVG, or PNG architecture artifacts unless the user explicitly asks for those formats.

## DSL syntax

Use this eraser-like DSL:

```arch
title "MCP Hot-Reload Subsystem Architecture"
direction right
folder "workspace mcp / hot reload"

Client Layer [icon: users, color: blue] {
  AI Agent [icon: ai, desc: Requests tools]
  User API [icon: api, desc: Opens config and triggers reloads]
}

Workspace MCP [icon: settings, color: amber] {
  Router [icon: api, desc: Routes tool calls]
  Registry [icon: database, desc: Tracks status, tools, config]
  Lifecycle Manager [icon: worker, desc: Connects, disconnects, reloads]
}

Persistence [icon: database, color: purple] {
  mcp_config.json [icon: file, desc: MCP config file]
  State Store [icon: database]
}

AI Agent > Router: call tool
User API > Lifecycle Manager: manage
Router > Registry: lookup
Registry > mcp_config.json: read/write
Registry > State Store: persist
```

Supported basics:

- `title "Name"` sets the graph title.
- `folder "Area / Subarea"` nests the graph in the Architecture sidebar.
- `direction right`, `direction down`, `direction left`, or `direction up` controls layout.
- `Container [icon: box, color: amber] { ... }` creates a group/container.
- `Node [icon: api, desc: Short description]` creates a node.
- `A > B: label` creates a directional edge.
- `A -- B: label` creates a dependency edge.
- `A <> B: label` creates bidirectional call edges.

## Icon naming

Use simple, stable icon aliases. The renderer resolves aliases through LikeC4 icons, styled-icons simple-icons, and semantic fallbacks.

When a node or container title names a real provider, product, framework, database, cloud service, or company, prefer that exact lowercase slug as the icon alias. For example, use `Appwrite [icon: appwrite]`, `Vercel [icon: vercel]`, or `React App [icon: react]` instead of generic `service`, `cloud`, or `client` icons. The renderer can infer package icons from titles when a generic fallback is used, but explicit brand aliases are best.

Preferred semantic aliases:

- `api`, `server`, `service`, `worker`, `database`, `storage`, `queue`, `cache`, `router`
- `auth`, `security`, `users`, `client`, `browser`, `terminal`, `settings`, `folder`, `file`
- `ai`, `flow`, `group`, `external`, `cloud`, `subscription`, `webhook`

Cloud service aliases:

- AWS: `aws:s3`, `aws:lambda`, `aws:rds`, `aws:dynamodb`, `aws:ec2`, `aws:ecs`, `aws:eks`, `aws:sqs`, `aws:sns`, `aws:api-gateway`, `aws:cloudfront`, `aws:cloudwatch`, `aws:iam`, `aws:vpc`
- GCP: `gcp:cloud-run`, `gcp:cloud-storage`, `gcp:cloud-sql`, `gcp:pubsub`, `gcp:bigquery`, `gcp:gke`
- Azure: `azure:functions`, `azure:blob-storage`, `azure:cosmosdb`, `azure:postgresql`, `azure:redis`, `azure:service-bus`, `azure:aks`

Tech and company aliases:

- `github`, `github-actions`, `docker`, `kubernetes`, `nginx`, `postgres`, `redis`, `mongodb`, `cockroachdb`
- `appwrite`, `stripe`, `supabase`, `cloudflare`, `auth0`, `nodejs`, `nextjs`, `typescript`, `react`, `vercel`, `openai`, `anthropic`

The list above is not exhaustive. Any installed LikeC4 icon slug from `aws`, `azure`, `gcp`, `tech`, or `bootstrap`, and any installed styled-icons simple-icons brand slug, can be used directly when it matches the node/container name.

If an exact icon is unknown, use the best semantic alias. The graph should still render with a clean fallback.

## Good graph style

- Keep node names short and descriptions useful.
- Use containers for ownership or runtime boundaries, not decoration.
- Prefer readable labels on important edges.
- Avoid overloading one graph. Split deployment, auth flow, billing flow, and subsystem internals into separate graphs when needed.
- Architecture files are for humans and agents: optimize for understanding, debugging, and future planning.
"##;

const ARCHITECTURE_ICON_REFERENCE: &str = r##"{
  "kind": "architecture_icon_alias_reference",
  "version": 1,
  "preferredSyntax": "icon: alias or icon: namespace:name",
  "notes": [
    "Use simple aliases first. The renderer resolves LikeC4 icons, styled-icons simple-icons, and semantic fallbacks.",
    "When a node or container title names a real provider, product, framework, cloud service, database, or company, prefer that exact lowercase slug as the icon alias.",
    "If an exact logo is unknown, use a semantic fallback such as api, server, database, storage, queue, worker, external, or service. The renderer also tries to infer installed package icons from titles when a generic fallback is used."
  ],
  "packageResolution": {
    "likec4": "Any installed @likec4/icons slug in aws, azure, gcp, tech, or bootstrap can be used, for example appwrite, appwrite-icon, aws:s3, gcp:cloud-run, or azure:functions.",
    "styledSimpleIcons": "Any installed @styled-icons/simple-icons brand/component can be used by simple slug, for example appwrite, cockroachlabs, vercel, react, stripe, or supabase.",
    "titleInference": "If icon is missing or generic, the renderer also checks the node/container title and strips common suffixes such as SDK, API, Service, App, Client, Server, Database, Queue, and Worker before falling back."
  },
  "semantic": [
    "ai",
    "api",
    "auth",
    "browser",
    "cache",
    "client",
    "cloud",
    "database",
    "external",
    "file",
    "flow",
    "folder",
    "group",
    "queue",
    "router",
    "security",
    "server",
    "service",
    "settings",
    "storage",
    "subscription",
    "terminal",
    "users",
    "webhook",
    "worker"
  ],
  "aws": [
    "aws:api-gateway",
    "aws:cloudfront",
    "aws:cloudwatch",
    "aws:dynamodb",
    "aws:ec2",
    "aws:ecr",
    "aws:ecs",
    "aws:eks",
    "aws:eventbridge",
    "aws:iam",
    "aws:kinesis",
    "aws:kms",
    "aws:lambda",
    "aws:rds",
    "aws:route53",
    "aws:s3",
    "aws:secrets-manager",
    "aws:sns",
    "aws:sqs",
    "aws:vpc"
  ],
  "gcp": [
    "gcp:bigquery",
    "gcp:cloud-run",
    "gcp:cloud-sql",
    "gcp:cloud-storage",
    "gcp:gke",
    "gcp:pubsub"
  ],
  "azure": [
    "azure:aks",
    "azure:blob-storage",
    "azure:cosmosdb",
    "azure:functions",
    "azure:postgresql",
    "azure:redis",
    "azure:service-bus",
    "azure:sql",
    "azure:storage"
  ],
  "techAndCompany": [
    "anthropic",
    "appwrite",
    "auth0",
    "cloudflare",
    "cockroachdb",
    "docker",
    "github",
    "github-actions",
    "kubernetes",
    "mongodb",
    "nextjs",
    "nginx",
    "nodejs",
    "openai",
    "postgres",
    "react",
    "redis",
    "stripe",
    "supabase",
    "typescript",
    "vercel"
  ],
  "examples": [
    "Appwrite [icon: appwrite, desc: Backend-as-a-service platform]",
    "API [icon: api, desc: Request handling]",
    "Object Store [icon: aws:s3, desc: Stores uploads]",
    "CockroachDB [icon: cockroachdb, desc: Durable SQL state]",
    "GitHub Actions [icon: github-actions, desc: CI pipeline]"
  ]
}
"##;

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct ArchitectureRepositoryEntry {
    id: String,
    name: String,
    path: String,
    relative_path: String,
    has_git: bool,
    architecture_root: String,
    graph_count: usize,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ArchitectureRepositoryList {
    root_directory: String,
    repositories: Vec<ArchitectureRepositoryEntry>,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct ArchitectureGraphSummary {
    id: String,
    title: String,
    kind: String,
    group_path: Vec<String>,
    node_count: usize,
    edge_count: usize,
    created_at: String,
    updated_at: String,
    file_path: String,
    source_format: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ArchitectureGraphList {
    repo_path: String,
    architecture_root: String,
    graphs: Vec<ArchitectureGraphSummary>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ArchitectureGraphSaveResult {
    repo_path: String,
    architecture_root: String,
    graph_id: String,
    file_path: String,
    graph: Value,
}

fn architecture_now_millis() -> String {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis().to_string())
        .unwrap_or_else(|_| "0".to_string())
}

fn architecture_modified_millis(path: &Path) -> String {
    fs::metadata(path)
        .ok()
        .and_then(|metadata| metadata.modified().ok())
        .and_then(|modified| modified.duration_since(UNIX_EPOCH).ok())
        .map(|duration| duration.as_millis().to_string())
        .unwrap_or_else(architecture_now_millis)
}

fn architecture_slug(value: &str) -> String {
    let mut output = String::new();
    let mut last_separator = false;

    for character in value.chars() {
        if output.len() >= ARCHITECTURE_GRAPH_ID_MAX {
            break;
        }
        if character.is_ascii_alphanumeric() {
            output.push(character.to_ascii_lowercase());
            last_separator = false;
        } else if !last_separator && !output.is_empty() {
            output.push('-');
            last_separator = true;
        }
    }

    while output.ends_with('-') {
        output.pop();
    }

    output
}

fn architecture_graph_id_from_graph(graph: &Value) -> Result<String, String> {
    let raw = graph
        .get("id")
        .and_then(Value::as_str)
        .or_else(|| graph.get("title").and_then(Value::as_str))
        .unwrap_or_default();
    let graph_id = architecture_slug(raw);
    if graph_id.is_empty() {
        return Err("Architecture graph requires a non-empty id or title.".to_string());
    }
    Ok(graph_id)
}

fn architecture_agents_root(repo: &Path) -> PathBuf {
    repo.join(".agents").join("architectures")
}

fn architecture_agent_guide_path(repo: &Path) -> PathBuf {
    architecture_agents_root(repo).join(ARCHITECTURE_AGENT_GUIDE_FILENAME)
}

fn architecture_icon_reference_path(repo: &Path) -> PathBuf {
    architecture_agents_root(repo).join(ARCHITECTURE_ICON_REFERENCE_FILENAME)
}

fn architecture_write_generated_reference_file(
    path: &Path,
    content: &str,
    label: &str,
) -> Result<(), String> {
    if fs::read_to_string(path).is_ok_and(|existing| existing == content) {
        return Ok(());
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("Unable to create architecture {label} directory: {error}"))?;
    }

    let temp_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .map(|value| format!("{value}.tmp"))
        .unwrap_or_else(|| "architecture-reference.tmp".to_string());
    let temp_path = path.with_file_name(temp_name);
    fs::write(&temp_path, content)
        .map_err(|error| format!("Unable to write architecture {label}: {error}"))?;
    if path.exists() {
        fs::remove_file(path)
            .map_err(|error| format!("Unable to replace architecture {label}: {error}"))?;
    }
    fs::rename(&temp_path, path)
        .map_err(|error| format!("Unable to commit architecture {label}: {error}"))
}

pub(crate) fn ensure_architecture_agent_guide(repo: &Path) -> Result<(), String> {
    let root = architecture_agents_root(repo);
    fs::create_dir_all(&root)
        .map_err(|error| format!("Unable to create architecture agent guide directory: {error}"))?;
    let _ = ensure_workspace_agents_gitignore(repo);
    architecture_write_generated_reference_file(
        &architecture_agent_guide_path(repo),
        ARCHITECTURE_AGENT_GUIDE,
        "agent guide",
    )?;
    architecture_write_generated_reference_file(
        &architecture_icon_reference_path(repo),
        ARCHITECTURE_ICON_REFERENCE,
        "icon reference",
    )
}

fn architecture_graphs_root(repo: &Path, create: bool) -> Result<PathBuf, String> {
    let root = architecture_agents_root(repo);
    let graphs_root = root.join("graphs");
    if create {
        fs::create_dir_all(&graphs_root)
            .map_err(|error| format!("Unable to create architecture graph directory: {error}"))?;
        ensure_architecture_agent_guide(repo)?;
    }
    Ok(graphs_root)
}

fn architecture_arch_path(repo: &Path, graph_id: &str) -> PathBuf {
    architecture_agents_root(repo)
        .join("graphs")
        .join(format!("{graph_id}.arch"))
}

fn architecture_json_path(repo: &Path, graph_id: &str) -> PathBuf {
    architecture_agents_root(repo)
        .join("graphs")
        .join(format!("{graph_id}.json"))
}

fn architecture_clean_line(value: &str) -> String {
    let mut in_quote = false;
    let mut output = String::new();
    let mut previous = '\0';
    let chars: Vec<char> = value.chars().collect();
    let mut index = 0usize;

    while index < chars.len() {
        let character = chars[index];
        if character == '"' && previous != '\\' {
            in_quote = !in_quote;
        }
        if !in_quote && character == '/' && chars.get(index + 1) == Some(&'/') {
            break;
        }
        if !in_quote && character == '#' {
            break;
        }
        output.push(character);
        previous = character;
        index += 1;
    }

    output.trim().to_string()
}

fn architecture_unquote(value: &str) -> String {
    let trimmed = value.trim();
    if trimmed.len() >= 2 && trimmed.starts_with('"') && trimmed.ends_with('"') {
        trimmed[1..trimmed.len() - 1]
            .replace("\\\"", "\"")
            .trim()
            .to_string()
    } else {
        trimmed.to_string()
    }
}

fn architecture_parse_title(source: &str, fallback_id: &str) -> String {
    for line in source.lines().map(architecture_clean_line) {
        if let Some(rest) = line.strip_prefix("title ") {
            let title = architecture_unquote(rest);
            if !title.is_empty() {
                return title;
            }
        }
    }

    fallback_id
        .split('-')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => format!("{}{}", first.to_ascii_uppercase(), chars.as_str()),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn architecture_parse_group_path(source: &str) -> Vec<String> {
    for line in source.lines().map(architecture_clean_line) {
        let Some(rest) = line
            .strip_prefix("folder ")
            .or_else(|| line.strip_prefix("groupPath "))
            .or_else(|| line.strip_prefix("path "))
        else {
            continue;
        };
        return architecture_group_path_from_text(rest);
    }
    Vec::new()
}

fn architecture_group_path_from_text(value: &str) -> Vec<String> {
    architecture_unquote(value)
        .split(&['/', '>'][..])
        .map(str::trim)
        .filter(|part| !part.is_empty())
        .take(12)
        .map(ToString::to_string)
        .collect()
}

fn architecture_source_counts(source: &str) -> (usize, usize) {
    let mut node_count = 0usize;
    let mut edge_count = 0usize;

    for line in source.lines().map(architecture_clean_line) {
        if line.is_empty()
            || line == "}"
            || line.starts_with("title ")
            || line.starts_with("folder ")
            || line.starts_with("groupPath ")
            || line.starts_with("path ")
            || line.starts_with("direction ")
            || line.starts_with("colorMode ")
            || line.starts_with("styleMode ")
            || line.starts_with("typeface ")
            || line.starts_with("legend ")
            || line.starts_with('[')
        {
            continue;
        }
        if line.contains(">")
            || line.contains("<")
            || line.contains("--")
            || (line.contains(" - ") && !line.ends_with('{'))
        {
            edge_count += 1;
        } else {
            node_count += 1;
        }
    }

    (node_count, edge_count)
}

fn architecture_graph_group_path(graph: &Value) -> Vec<String> {
    graph
        .get("groupPath")
        .or_else(|| graph.get("group_path"))
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(str::trim)
                .filter(|item| !item.is_empty())
                .take(12)
                .map(ToString::to_string)
                .collect()
        })
        .unwrap_or_default()
}

fn architecture_summary_from_arch(path: &Path, fallback_id: &str) -> Option<ArchitectureGraphSummary> {
    let metadata = fs::symlink_metadata(path).ok()?;
    if metadata.file_type().is_symlink()
        || !metadata.is_file()
        || metadata.len() > ARCHITECTURE_GRAPH_MAX_BYTES
    {
        return None;
    }
    let source = fs::read_to_string(path).ok()?;
    let title = architecture_parse_title(&source, fallback_id);
    let group_path = architecture_parse_group_path(&source);
    let (node_count, edge_count) = architecture_source_counts(&source);
    let updated_at = architecture_modified_millis(path);

    Some(ArchitectureGraphSummary {
        id: fallback_id.to_string(),
        title,
        kind: "architecture".to_string(),
        group_path,
        node_count,
        edge_count,
        created_at: updated_at.clone(),
        updated_at,
        file_path: workspace_path_display(path),
        source_format: "eraserDsl".to_string(),
    })
}

fn architecture_graph_summary_from_value(
    graph: &Value,
    fallback_id: &str,
    file_path: &Path,
) -> Option<ArchitectureGraphSummary> {
    let object = graph.as_object()?;
    let id = graph
        .get("id")
        .and_then(Value::as_str)
        .map(architecture_slug)
        .filter(|value| !value.is_empty())
        .unwrap_or_else(|| fallback_id.to_string());
    let title = object
        .get("title")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .unwrap_or(id.as_str())
        .to_string();
    let kind = object
        .get("kind")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .unwrap_or("architecture")
        .to_string();
    let node_count = object
        .get("nodes")
        .and_then(Value::as_array)
        .map(Vec::len)
        .unwrap_or(0);
    let edge_count = object
        .get("edges")
        .and_then(Value::as_array)
        .map(Vec::len)
        .unwrap_or(0);
    let created_at = object
        .get("createdAt")
        .or_else(|| object.get("created_at"))
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string();
    let updated_at = object
        .get("updatedAt")
        .or_else(|| object.get("updated_at"))
        .and_then(Value::as_str)
        .map(ToString::to_string)
        .unwrap_or_else(|| architecture_modified_millis(file_path));

    Some(ArchitectureGraphSummary {
        id,
        title,
        kind,
        group_path: architecture_graph_group_path(graph),
        node_count,
        edge_count,
        created_at,
        updated_at,
        file_path: workspace_path_display(file_path),
        source_format: "json".to_string(),
    })
}

fn architecture_read_json_graph_file(path: &Path) -> Result<Value, String> {
    let metadata = fs::metadata(path)
        .map_err(|error| format!("Unable to inspect architecture graph file: {error}"))?;
    if !metadata.is_file() {
        return Err("Architecture graph path is not a file.".to_string());
    }
    if metadata.len() > ARCHITECTURE_GRAPH_MAX_BYTES {
        return Err("Architecture graph file is too large.".to_string());
    }
    let bytes = fs::read(path)
        .map_err(|error| format!("Unable to read architecture graph file: {error}"))?;
    serde_json::from_slice::<Value>(&bytes)
        .map_err(|error| format!("Unable to parse architecture graph JSON: {error}"))
}

fn architecture_read_arch_graph(path: &Path, graph_id: &str) -> Result<Value, String> {
    let metadata = fs::metadata(path)
        .map_err(|error| format!("Unable to inspect architecture DSL file: {error}"))?;
    if !metadata.is_file() {
        return Err("Architecture graph path is not a file.".to_string());
    }
    if metadata.len() > ARCHITECTURE_GRAPH_MAX_BYTES {
        return Err("Architecture DSL file is too large.".to_string());
    }
    let source = fs::read_to_string(path)
        .map_err(|error| format!("Unable to read architecture DSL file: {error}"))?;
    let title = architecture_parse_title(&source, graph_id);
    let group_path = architecture_parse_group_path(&source);
    let (node_count, edge_count) = architecture_source_counts(&source);
    let updated_at = architecture_modified_millis(path);

    Ok(json!({
        "id": graph_id,
        "title": title,
        "kind": "architecture",
        "groupPath": group_path,
        "source": source,
        "sourceFormat": "eraserDsl",
        "version": 2,
        "createdAt": updated_at,
        "updatedAt": updated_at,
        "filePath": workspace_path_display(path),
        "nodeCount": node_count,
        "edgeCount": edge_count,
    }))
}

fn architecture_graph_summaries(repo: &Path) -> Result<Vec<ArchitectureGraphSummary>, String> {
    let graphs_root = architecture_graphs_root(repo, false)?;
    if !graphs_root.exists() {
        return Ok(Vec::new());
    }

    let read_dir = fs::read_dir(&graphs_root)
        .map_err(|error| format!("Unable to list architecture graphs: {error}"))?;
    let mut graphs = Vec::new();
    let mut arch_ids = HashSet::new();
    let mut json_candidates: Vec<(String, PathBuf)> = Vec::new();

    for entry in read_dir {
        let entry = match entry {
            Ok(entry) => entry,
            Err(_) => continue,
        };
        let path = entry.path();
        let Some(extension) = path.extension().and_then(|value| value.to_str()) else {
            continue;
        };
        let fallback_id = path
            .file_stem()
            .and_then(|value| value.to_str())
            .map(architecture_slug)
            .filter(|value| !value.is_empty())
            .unwrap_or_else(|| "architecture".to_string());

        match extension {
            "arch" => {
                if let Some(summary) = architecture_summary_from_arch(&path, &fallback_id) {
                    arch_ids.insert(summary.id.clone());
                    graphs.push(summary);
                }
            }
            "json" => {
                json_candidates.push((fallback_id, path));
            }
            _ => {}
        }
    }

    for (fallback_id, path) in json_candidates {
        if arch_ids.contains(&fallback_id) {
            continue;
        }
        let Ok(metadata) = fs::symlink_metadata(&path) else {
            continue;
        };
        if metadata.file_type().is_symlink()
            || !metadata.is_file()
            || metadata.len() > ARCHITECTURE_GRAPH_MAX_BYTES
        {
            continue;
        }
        let Ok(graph) = architecture_read_json_graph_file(&path) else {
            continue;
        };
        if let Some(summary) = architecture_graph_summary_from_value(&graph, &fallback_id, &path) {
            graphs.push(summary);
        }
    }

    graphs.sort_by(|left, right| {
        right
            .updated_at
            .cmp(&left.updated_at)
            .then_with(|| left.title.cmp(&right.title))
    });
    Ok(graphs)
}

fn architecture_write_index(
    repo: &Path,
    graphs: &[ArchitectureGraphSummary],
) -> Result<(), String> {
    ensure_architecture_agent_guide(repo)?;
    let root = architecture_agents_root(repo);
    fs::create_dir_all(&root)
        .map_err(|error| format!("Unable to create architecture index directory: {error}"))?;
    let index = json!({
        "kind": "architecture_index",
        "version": 2,
        "updatedAt": architecture_now_millis(),
        "sourceFormat": "eraserDsl",
        "graphs": graphs,
    });
    let bytes = serde_json::to_vec_pretty(&index)
        .map_err(|error| format!("Unable to serialize architecture index: {error}"))?;
    fs::write(root.join("index.json"), bytes)
        .map_err(|error| format!("Unable to write architecture index: {error}"))
}

fn architecture_graph_count(repo: &Path) -> usize {
    architecture_graph_summaries(repo)
        .map(|graphs| graphs.len())
        .unwrap_or(0)
}

fn architecture_repository_entry(
    workspace_root: &Path,
    repo: &Path,
    relative_path: String,
    has_git: bool,
) -> ArchitectureRepositoryEntry {
    let name = repo
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or("repo")
        .to_string();
    let path = workspace_path_display(repo);
    let architecture_root = workspace_path_display(&architecture_agents_root(repo));
    let id = normalized_path_key(repo);
    let relative_path = if relative_path.is_empty() {
        if normalized_path_key(workspace_root) == id {
            ".".to_string()
        } else {
            path.clone()
        }
    } else {
        relative_path
    };

    ArchitectureRepositoryEntry {
        id,
        name,
        path,
        relative_path,
        has_git,
        architecture_root,
        graph_count: architecture_graph_count(repo),
    }
}

fn architecture_repositories_blocking(
    root_directory: Option<String>,
) -> Result<ArchitectureRepositoryList, String> {
    let root = resolve_workspace_root_directory(root_directory.as_deref())?;
    let mounts = workspace_project_mounts(&root);
    let mut seen = HashSet::new();
    let mut repositories = Vec::new();

    for mount in mounts.iter().filter(|mount| mount.has_git) {
        let key = normalized_path_key(&mount.root_path);
        if seen.insert(key) {
            repositories.push(architecture_repository_entry(
                &root,
                &mount.root_path,
                mount.workspace_relative_path.clone(),
                mount.has_git,
            ));
        }
    }

    if repositories.is_empty() {
        let key = normalized_path_key(&root);
        if seen.insert(key) {
            let has_git = workspace_is_exact_git_root(&root);
            repositories.push(architecture_repository_entry(
                &root,
                &root,
                ".".to_string(),
                has_git,
            ));
        }
    }

    repositories.sort_by(|left, right| {
        left.relative_path
            .cmp(&right.relative_path)
            .then_with(|| left.name.cmp(&right.name))
    });

    Ok(ArchitectureRepositoryList {
        root_directory: workspace_path_display(&root),
        repositories,
    })
}

fn architecture_graphs_list_blocking(repo_path: String) -> Result<ArchitectureGraphList, String> {
    let repo = resolve_workspace_root_directory(Some(repo_path.as_str()))?;
    let graphs = architecture_graph_summaries(&repo)?;
    if architecture_agents_root(&repo).exists() {
        let _ = ensure_architecture_agent_guide(&repo);
        let _ = architecture_write_index(&repo, &graphs);
    }
    Ok(ArchitectureGraphList {
        repo_path: workspace_path_display(&repo),
        architecture_root: workspace_path_display(&architecture_agents_root(&repo)),
        graphs,
    })
}

fn architecture_graph_read_blocking(repo_path: String, graph_id: String) -> Result<Value, String> {
    let repo = resolve_workspace_root_directory(Some(repo_path.as_str()))?;
    let graph_id = architecture_slug(&graph_id);
    if graph_id.is_empty() {
        return Err("Architecture graph id is required.".to_string());
    }
    let arch_path = architecture_arch_path(&repo, &graph_id);
    if arch_path.exists() {
        return architecture_read_arch_graph(&arch_path, &graph_id);
    }
    let json_path = architecture_json_path(&repo, &graph_id);
    if json_path.exists() {
        return architecture_read_json_graph_file(&json_path);
    }
    Err("Architecture graph was not found.".to_string())
}

fn architecture_graph_save_blocking(
    repo_path: String,
    mut graph: Value,
) -> Result<ArchitectureGraphSaveResult, String> {
    let repo = resolve_workspace_root_directory(Some(repo_path.as_str()))?;
    let graph_id = architecture_graph_id_from_graph(&graph)?;
    let graphs_root = architecture_graphs_root(&repo, true)?;
    let now = architecture_now_millis();

    if let Some(source) = graph.get("source").and_then(Value::as_str) {
        if source.as_bytes().len() as u64 > ARCHITECTURE_GRAPH_MAX_BYTES {
            return Err("Architecture DSL source is too large.".to_string());
        }
        let graph_path = graphs_root.join(format!("{graph_id}.arch"));
        let temp_path = graph_path.with_extension("arch.tmp");
        fs::write(&temp_path, source)
            .map_err(|error| format!("Unable to write architecture DSL file: {error}"))?;
        if graph_path.exists() {
            fs::remove_file(&graph_path)
                .map_err(|error| format!("Unable to replace architecture DSL file: {error}"))?;
        }
        fs::rename(&temp_path, &graph_path)
            .map_err(|error| format!("Unable to commit architecture DSL file: {error}"))?;

        let object = graph
            .as_object_mut()
            .ok_or_else(|| "Architecture graph must be a JSON object.".to_string())?;
        object.insert("id".to_string(), Value::String(graph_id.clone()));
        object.insert("sourceFormat".to_string(), Value::String("eraserDsl".to_string()));
        object.insert("updatedAt".to_string(), Value::String(now.clone()));
        object
            .entry("createdAt".to_string())
            .or_insert_with(|| Value::String(now.clone()));
        object.insert(
            "filePath".to_string(),
            Value::String(workspace_path_display(&graph_path)),
        );

        let graphs = architecture_graph_summaries(&repo)?;
        let _ = architecture_write_index(&repo, &graphs);

        return Ok(ArchitectureGraphSaveResult {
            repo_path: workspace_path_display(&repo),
            architecture_root: workspace_path_display(&architecture_agents_root(&repo)),
            graph_id,
            file_path: workspace_path_display(&graph_path),
            graph,
        });
    }

    let graph_path = graphs_root.join(format!("{graph_id}.json"));
    let object = graph
        .as_object_mut()
        .ok_or_else(|| "Architecture graph must be a JSON object.".to_string())?;

    object.insert("id".to_string(), Value::String(graph_id.clone()));
    object
        .entry("kind".to_string())
        .or_insert_with(|| Value::String("architecture".to_string()));
    object
        .entry("version".to_string())
        .or_insert_with(|| Value::Number(1.into()));
    object
        .entry("createdAt".to_string())
        .or_insert_with(|| Value::String(now.clone()));
    object.insert("updatedAt".to_string(), Value::String(now));

    let bytes = serde_json::to_vec_pretty(&graph)
        .map_err(|error| format!("Unable to serialize architecture graph: {error}"))?;
    if bytes.len() as u64 > ARCHITECTURE_GRAPH_MAX_BYTES {
        return Err("Architecture graph is too large.".to_string());
    }

    let temp_path = graph_path.with_extension("json.tmp");
    fs::write(&temp_path, bytes)
        .map_err(|error| format!("Unable to write architecture graph: {error}"))?;
    if graph_path.exists() {
        fs::remove_file(&graph_path)
            .map_err(|error| format!("Unable to replace architecture graph: {error}"))?;
    }
    fs::rename(&temp_path, &graph_path)
        .map_err(|error| format!("Unable to commit architecture graph: {error}"))?;

    let graphs = architecture_graph_summaries(&repo)?;
    let _ = architecture_write_index(&repo, &graphs);

    Ok(ArchitectureGraphSaveResult {
        repo_path: workspace_path_display(&repo),
        architecture_root: workspace_path_display(&architecture_agents_root(&repo)),
        graph_id,
        file_path: workspace_path_display(&graph_path),
        graph,
    })
}

pub(crate) fn architecture_icon_reference_value(repo_path: String) -> Result<Value, String> {
    let repo = resolve_workspace_root_directory(Some(repo_path.as_str()))?;
    ensure_architecture_agent_guide(&repo)?;
    let mut reference = serde_json::from_str::<Value>(ARCHITECTURE_ICON_REFERENCE)
        .map_err(|error| format!("Unable to parse architecture icon reference: {error}"))?;
    if let Some(object) = reference.as_object_mut() {
        object.insert(
            "repoPath".to_string(),
            Value::String(workspace_path_display(&repo)),
        );
        object.insert(
            "referencePath".to_string(),
            Value::String(workspace_path_display(&architecture_icon_reference_path(&repo))),
        );
    }
    Ok(reference)
}

pub(crate) fn architecture_context_value(repo_path: String) -> Result<Value, String> {
    let repo = resolve_workspace_root_directory(Some(repo_path.as_str()))?;
    ensure_architecture_agent_guide(&repo)?;
    let graphs = architecture_graph_summaries(&repo)?;
    let _ = architecture_write_index(&repo, &graphs);
    let architecture_root = architecture_agents_root(&repo);
    Ok(json!({
        "kind": "architecture_context",
        "version": 1,
        "repoPath": workspace_path_display(&repo),
        "architectureRoot": workspace_path_display(&architecture_root),
        "graphsRoot": workspace_path_display(&architecture_root.join("graphs")),
        "indexPath": workspace_path_display(&architecture_root.join("index.json")),
        "agentGuidePath": workspace_path_display(&architecture_agent_guide_path(&repo)),
        "iconReferencePath": workspace_path_display(&architecture_icon_reference_path(&repo)),
        "sourceFormat": "eraserDsl",
        "graphExtension": ".arch",
        "graphs": graphs,
        "contract": {
            "purpose": "Architecture graphs are repo-scoped Diff Forge artifacts for humans and agents.",
            "preferredMcpTools": [
                "coordination-kernel.architecture_context",
                "coordination-kernel.architecture_list",
                "coordination-kernel.architecture_icon_reference"
            ],
            "workflow": [
                "Call architecture_context or architecture_list before creating a new architecture.",
                "Read the closest existing .agents/architectures/graphs/*.arch file directly before modifying a known subsystem.",
                "Create or update .agents/architectures/graphs/*.arch with normal file edits using the eraser-like DSL.",
                "Write containers and nodes first, then edges, and save the file incrementally so the Architecture tab updates live.",
                "Use architecture_icon_reference when choosing cloud, tech, company, product, framework, or semantic icon aliases.",
                "Prefer exact provider/product/framework slugs such as appwrite, react, vercel, github, postgres, redis, or cockroachdb when a node/container title names that technology; semantic aliases are only fallbacks."
            ],
            "doNotCreateUnlessExplicitlyRequested": [
                "ARCHITECTURE.md",
                "docs/architecture.md",
                "docs/architecture.mmd",
                "Draw.io",
                "PNG",
                "SVG"
            ]
        },
        "dsl": {
            "title": "title \"Human-readable graph name\"",
            "folder": "folder \"Area / Subarea\"",
            "direction": "direction right | down | left | up",
            "container": "Runtime Boundary [icon: cloud, color: blue] { ... }",
            "node": "API [icon: api, desc: Request handling]",
            "edges": [
                "Client > API: request",
                "API -- Database: dependency",
                "API <> Worker: bidirectional"
            ],
            "example": "title \"Subsystem Architecture\"\ndirection right\nfolder \"backend / subsystem\"\n\nClient [icon: users]\nAPI [icon: api, desc: Handles requests]\nDatabase [icon: database]\n\nClient > API: request\nAPI > Database: read/write"
        }
    }))
}

pub(crate) fn architecture_graphs_list_value(repo_path: String) -> Result<Value, String> {
    let list = architecture_graphs_list_blocking(repo_path)?;
    serde_json::to_value(list)
        .map_err(|error| format!("Unable to serialize architecture graph list: {error}"))
}

#[tauri::command]
async fn architecture_repositories(
    root_directory: Option<String>,
) -> Result<ArchitectureRepositoryList, String> {
    tauri::async_runtime::spawn_blocking(move || architecture_repositories_blocking(root_directory))
        .await
        .map_err(|error| format!("Architecture repository worker failed: {error}"))?
}

#[tauri::command]
async fn architecture_graphs_list(repo_path: String) -> Result<ArchitectureGraphList, String> {
    tauri::async_runtime::spawn_blocking(move || architecture_graphs_list_blocking(repo_path))
        .await
        .map_err(|error| format!("Architecture graph list worker failed: {error}"))?
}

#[tauri::command]
async fn architecture_graph_read(repo_path: String, graph_id: String) -> Result<Value, String> {
    tauri::async_runtime::spawn_blocking(move || {
        architecture_graph_read_blocking(repo_path, graph_id)
    })
    .await
    .map_err(|error| format!("Architecture graph read worker failed: {error}"))?
}

#[tauri::command]
async fn architecture_graph_save(
    repo_path: String,
    graph: Value,
) -> Result<ArchitectureGraphSaveResult, String> {
    tauri::async_runtime::spawn_blocking(move || {
        architecture_graph_save_blocking(repo_path, graph)
    })
    .await
    .map_err(|error| format!("Architecture graph save worker failed: {error}"))?
}
